def dia = new Date().getDay()
def dias_letras=
                [1: "Lunes",
                 2:  "Martes",
                 3: "Miercoles",
                 4: "Jueves",
                 5: "Viernes",
                 6: "Sabado",
                 7: "Domingo"]
pipeline
{
    agent any
    stages
    {
        stage('Luns')
        {
            steps
            {
            script
            {
		println dias_letras[dia]
                 if(dia == 2)
                 println "Este pipeline no se ejecuta los días martes"
            }
            }
        }
    }
}
